---
sidebar: sidebar
permalink: concept_overview.html
keywords: cloud tiering, overview, conceptual, value, features, backup, report, monitoring, health
summary: Cloud Tiering is a NetApp-managed service that can reduce your on-premises storage costs by automatically tiering inactive data to object storage in the cloud. This enables you to extend your data center to the public cloud without changing your application layer.
---

= Cloud Tiering overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp's Cloud Tiering service extends your data center to the public cloud by automatically tiering inactive data from ONTAP clusters to object storage. This frees valuable space on the cluster for more workloads, without making changes to the application layer. Cloud Tiering can reduce costs in your data center and enables a switch from a CAPEX model to an OPEX model.

The Cloud Tiering service leverages the capabilities of _FabricPool_. FabricPool is a NetApp Data Fabric technology that enables automated tiering of data to low-cost object storage. Active data remains on high-performance SSDs, while inactive data is tiered to low-cost object storage while preserving ONTAP data efficiencies.

Cloud Tiering offers automation, monitoring, reports, and a common management interface:

* Automation makes it easier to set up and manage data tiering from ONTAP clusters to the cloud
* A single pane of glass removes the need to independently manage FabricPool across several clusters
* Reports show the amount of active and inactive data on each cluster
* A tiering health status helps you identify and correct issues as they occur

For more details about the value that Cloud Tiering provides, https://cloud.netapp.com/cloud-tiering[check out the Cloud Tiering page on NetApp Cloud Central^].

NOTE: While Cloud Tiering can significantly reduce storage footprints, it is not a backup solution.
