---
redirect: occm/concept_cloud_tiering.html
sidebar: sidebar
permalink: concept_overview.html
keywords: cloud tiering, overview, conceptual, value, features, backup, report, monitoring, health
summary: NetApp's Cloud Tiering service extends your data center to the cloud by automatically tiering inactive data from ONTAP clusters to object storage. Without compromising on manageability and performance, Cloud Tiering efficiently manages your storage pool by seamlessly placing your data at the right tier at the right time, based on its usage.
---

= Cloud Tiering overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp's Cloud Tiering service extends your data center to the cloud by automatically tiering inactive data from ONTAP clusters to object storage. Without compromising on manageability and performance, Cloud Tiering efficiently manages your storage pool by seamlessly placing your data at the right tier at the right time, based on its usage.

The Cloud Tiering service leverages the capabilities of _FabricPool_. FabricPool is a NetApp Data Fabric technology that enables automated tiering of data to low-cost object storage. Active data remains on high-performance SSDs, while inactive data is tiered to low-cost object storage while preserving ONTAP data efficiencies.

Cloud Tiering offers automation, monitoring, reports, and a common management interface:

* Automation makes it easier to set up and manage data tiering from ONTAP clusters to the cloud
* A single pane of glass removes the need to independently manage FabricPool across several clusters
* Reports show the amount of active and inactive data on each cluster
* A tiering health status helps you identify and correct issues as they occur

For more details about the value that Cloud Tiering provides, https://cloud.netapp.com/cloud-tiering[check out the Cloud Tiering page on NetApp Cloud Central^].

NOTE: While Cloud Tiering can significantly reduce storage footprints, it is not a backup solution.
