---
sidebar: sidebar
permalink: concept_licensing.html
keywords: license, subscription, registering, paygo, byol, pay as you go, bring your own license, free trial, trial, controlled availability
summary: Cloud Tiering offers capacity-based licensing in a pay-as-you-go model. We plan to offer a bring your own license (BYOL) model in the coming months.
---

= How Cloud Tiering licenses work
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Tiering offers capacity-based licensing in a pay-as-you-go model. We plan to offer a bring your own license (BYOL) model in the coming months.

NOTE: We're currently charging for data that's tiered to AWS. At this time, there's no charging for data that's tiered to Azure or Google Cloud.

A 30-day free trial of Cloud Tiering starts when you set up tiering to your first cluster. You should subscribe to the Cloud Tiering service to ensure that there's no disruption of service after your free trial ends. When the trial ends, you'll be charged hourly according to the amount of data that you tier.

link:task_licensing.html[Learn how to subscribe from the AWS Marketplace].

==== What happens if my free trial ends and I don't subscribe?

No new data is tiered to object storage, but existing data is still available for access. Also, you can't set up data tiering for any additional clusters.
