---
sidebar: sidebar
permalink: concept_licensing.html
keywords: license, subscription, registering, paygo, byol, pay as you go, bring your own license, free trial, trial, controlled availability, aws marketplace, gcp marketplace, azure marketplace, aws paygo, azure paygo, gcp paygo
summary: A 30-day free trial of Cloud Tiering starts when you set up tiering to your first cluster. After that 30-day free trial ends, you'll need to pay for Cloud Tiering through a pay-as-you-go subscription, an ONTAP tiering license, or a combination of both.
---

= How Cloud Tiering licenses work
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Pay for Cloud Tiering through a pay-as-you-go subscription, an ONTAP tiering license called _FabricPool_, or a combination of both. A 30-day free trial is available for your first cluster.

== 30-day free trial

A 30-day free trial of Cloud Tiering starts when you set up tiering to your first cluster. After that 30-day free trial ends, you'll need to pay for Cloud Tiering through a pay-as-you-go subscription, an ONTAP tiering license, or a combination of both.

If your free trial ends and you haven't subscribed or added a license, then ONTAP no longer tiers cold data to object storage, but existing data is still available for access.

== Pay-as-you-go subscription

Cloud Tiering offers consumption-based licensing in a pay-as-you-go model. After subscribing through your cloud provider's marketplace, you pay per GB for data that's tiered--there’s no up-front payment. You are billed by your cloud provider through your monthly bill.

You should subscribe even if you have a free trial or if you bring your own license (BYOL):

* Subscribing ensures that there’s no disruption of service after your free trial ends.
+
When the trial ends, you’ll be charged hourly according to the amount of data that you tier.

* If your FabricPool license expires or if you tier more data than allowed by the license, then data tiering is never interrupted--it continues through your PAYGO subscription.
+
For example, if you have a 10 TB license, all capacity beyond the 10 TB is charged through the PAYGO subscription.

link:task_licensing.html[Learn how to set up a pay-as-you-go subscription].

== Bring your own license

You can purchase term-based or perpetual licenses directly from NetApp.

If you bring your own license, you'll need to add the FabricPool license to the cluster through ONTAP System Manager or the CLI. If a license is available on the cluster, then Cloud Tiering displays the license in the *Licensing* page.

TIP: In a future release, you'll be able to add FabricPool licenses to ONTAP directly from Cloud Tiering.

As noted above, we recommend that you set up a pay-as-you-go subscription, even if your cluster has a BYOL license.

mailto:ng-cloud-tiering@netapp.com?subject=Licensing[Contact us to purchase a license].
