---
sidebar: sidebar
permalink: concept_licensing.html
keywords: license, subscription, registering, paygo, byol, pay as you go, bring your own license, free trial, trial, controlled availability, aws marketplace, gcp marketplace, azure marketplace, aws paygo, azure paygo, gcp paygo
summary: Pay for Cloud Tiering through a pay-as-you-go subscription, an ONTAP tiering license called FabricPool, or a combination of both. A 30-day free trial is available for your first cluster if you don't have a license.
---

= How licensing works
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Pay for Cloud Tiering through a pay-as-you-go subscription, an ONTAP tiering license called _FabricPool_, or a combination of both. A 30-day free trial is available for your first cluster if you don't have a license.

NOTE: A license isn't required when tiering data to StorageGRID.

== 30-day free trial

If you don't have a FabricPool license, a 30-day free trial of Cloud Tiering starts when you set up tiering to your first cluster. After that 30-day free trial ends, you'll need to pay for Cloud Tiering through a pay-as-you-go subscription, a FabricPool license, or a combination of both.

If your free trial ends and you haven't subscribed or added a license, then ONTAP no longer tiers cold data to object storage, but existing data is still available for access.

== Pay-as-you-go subscription

Cloud Tiering offers consumption-based licensing in a pay-as-you-go model. After subscribing through your cloud provider's marketplace, you pay per GB for data that's tiered--there’s no up-front payment. You are billed by your cloud provider through your monthly bill.

You should subscribe even if you have a free trial or if you bring your own license (BYOL):

* Subscribing ensures that there’s no disruption of service after your free trial ends.
+
When the trial ends, you’ll be charged hourly according to the amount of data that you tier.

* If you tier more data than allowed by your FabricPool license, then data tiering continues through your pay-as-you-go subscription.
+
For example, if you have a 10 TB license, all capacity beyond the 10 TB is charged through the pay-as-you-go subscription.

You won't be charged from your pay-as-you-go subscription during your free trial or if you haven't exceeded your FabricPool license.

link:task_licensing.html[Learn how to set up a pay-as-you-go subscription].

== Bring your own license

Bring your own license by purchasing an ONTAP FabricPool license from NetApp. You can purchase term-based or perpetual licenses.

After you purchase a FabricPool license, you'll need to add it to the cluster, link:task_licensing.html#adding-a-tiering-license-to-ontap[which you can do directly from Cloud Tiering].

After you activate the license through Cloud Tiering, if you purchase additional add-on capacity at a later time, the license on the cluster is automatically updated with the new capacity. There's no need to apply a new NetApp License File (NLF) to the cluster.

As noted above, we recommend that you set up a pay-as-you-go subscription, even if your cluster has a BYOL license.

mailto:ng-cloud-tiering@netapp.com?subject=Licensing[Contact us to purchase a license].
