---
sidebar: sidebar
permalink: faq.html
keywords: faq, questions, requirements, service connector, object store, object storage, aws, azure, bucket, cluster, aggregate, s3, storage class, standard, inactive data reporting, auto, volume tiering policy, policy, tiering policy, snapshot, cold, inactive, infrequent
summary: This FAQ can help if you're just looking for a quick answer to a question.
---

= Cloud Tiering technical FAQ
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
This FAQ can help if you're just looking for a quick answer to a question.

== ONTAP

The following questions relate to ONTAP.

=== What are the requirements for my ONTAP cluster?

You need an AFF or FAS system with all-SSD aggregates running ONTAP 9.2 or later, and a network connection to object storage. For more details, see:

* link:task_preparing.html#preparing-your-ontap-clusters[Preparing to tier inactive data to AWS S3]
* link:task_preparing_azure.html#preparing-your-ontap-clusters[Preparing to tier inactive data to Azure Blob storage]

=== Does Cloud Tiering enable inactive data reporting?

Yes, Cloud Tiering enables inactive data reporting on each aggregate. This setting enables us to identify the amount of inactive data that can be tiered to low-cost object storage.

== Object storage

The following questions relate to object storage.

=== Which object storage providers are supported?

AWS S3 and Azure Blob storage are supported. Support for additional object storage providers will be added later.

=== Which regions are supported?

Most regions are supported.

* link:reference_aws_support.html[Supported AWS regions]
* link:reference_azure_support.html[Supported Azure regions]

=== Which S3 storage classes are supported?

Cloud Tiering supports data tiering to two S3 storage classes: Standard and Standard-Infrequent Access. See link:reference_aws_support.html[Supported S3 storage classes] for more details.

=== Which Azure Blob access tiers are supported?

Cloud Tiering automatically uses the _Hot_ access tier for your inactive data. No other access tiers are supported at this time.

=== Does Cloud Tiering create one object store for the entire cluster or one per aggregate?

One object store for the entire cluster.

=== Can I apply policies to my object store to move data around independent of tiering?

No, Cloud Tiering does not support object lifecycle management rules that move or delete data from object stores.

== NetApp Service Connector

The following questions relate to the NetApp Service Connector.

=== What is the Service Connector?

The Service Connector is NetApp software that communicates with ONTAP clusters to discover information about active and inactive data, and to set up data tiering. For more details, see link:concept_architecture.html[How Cloud Tiering works].

=== Where can I run the Service Connector?

In an AWS VPC when tiering data to S3, and in an Azure VNet when tiering data to Blob storage.

=== How do you name the instance/virtual machine for the Service Connector?

The name of the Service Connector is prefixed with "Service-connector."

== Networking

The following questions relate to networking.

=== What are the networking requirements?

You need a connection between your ONTAP cluster and the object storage provider. The NetApp Service Connector needs an outbound connection to your ONTAP clusters, to the object store, and to the Cloud Tiering service.

For more details, see:

* link:task_preparing.html[Preparing to tier inactive data to AWS S3]
* link:task_preparing_azure.html[Preparing to tier inactive data to Azure Blob storage]

== Permissions

The following questions relate to permissions.

=== What permissions are required in AWS?

Permissions are needed link:task_preparing.html#setting-up-an-aws-account-for-the-service-connector[to deploy the Service Connector in an AWS VPC] and link:task_preparing.html#preparing-aws-s3-for-data-tiering[to manage the S3 bucket].

=== What permissions are required in Azure?

Permissions are needed link:task_preparing_azure.html#granting-azure-permissions[to deploy the Service Connector in an Azure VNet].

During deployment, Cloud Tiering creates and assigns a role to the Service Connector that provides the required permissions to tier data to Azure Blob storage.
