---
sidebar: sidebar
permalink: faq.html
keywords: faq, questions, requirements, service connector, object store, object storage, aws, azure, bucket, cluster, aggregate, s3, storage class, standard, inactive data reporting, auto, volume tiering policy, policy, tiering policy, snapshot, cold, inactive, infrequent
summary: This FAQ can help if you're just looking for a quick answer to a question.
---

= Cloud Tiering technical FAQ
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
This FAQ can help if you're just looking for a quick answer to a question.

== What are the requirements for my ONTAP cluster?

You need a NetApp AFF system running ONTAP 9.4 or later, with a network connection to your object storage provider. For details, see link:task_preparing.html#preparing-your-ontap-cluster[Preparing your ONTAP cluster].

== Which object storage providers are supported?

AWS S3 is supported at this time. Support is coming soon for Microsoft Azure, Google Cloud Platform, and StorageGRID Webscale.

== Which AWS regions are supported?

include::/_include/s3regions.adoc[]

== Which S3 storage classes are supported?

Cloud Tiering supports data tiering to the S3 Standard storage class. Support for other storage classes is coming soon.

== Does Cloud Tiering create one S3 bucket for the entire cluster or one per aggregate?

One bucket for the entire cluster.

== What is the Service Connector?

The Service Connector is NetApp software that communicates with ONTAP clusters to discover information about active and inactive data, and to set up data tiering. For more details, see link:concept_architecture.html[How Cloud Tiering works].

== Where can I run the Service Connector?

In AWS. Support for Microsoft Azure is coming soon.

== How do you name the EC2 instance for the Service Connector?

The EC2 instance name for the Service Connector is prefixed with "Service-connector."

== What are the networking requirements?

You need a connection between your ONTAP cluster and the object storage provider. The NetApp Service Connector needs an outbound connection to your ONTAP clusters and to the Cloud Tiering service. For more details, see link:task_preparing.html[Preparing your environment].

== What cloud provider permissions are required?

Permissions are needed link:task_preparing.html#setting-up-an-aws-account-for-the-service-connector[to deploy the Service Connector in AWS] and link:task_preparing.html#preparing-aws-s3-for-data-tiering[to manage the S3 bucket].

== Which volume tiering policy does Cloud Tiering apply to each volume?

When you select the volumes that you want to tier, Cloud Tiering applies the _Auto_ volume tiering policy to each volume. This policy tiers Snapshot copies and cold user data from the active file system to object storage. For more details, see link:concept_architecture.html[How Cloud Tiering works].

== Does Cloud Tiering enable inactive data reporting?

Yes, Cloud Tiering enables inactive data reporting on each aggregate. This setting enables us to identify the amount of inactive data that can be tiered to low-cost object storage.
