---
sidebar: sidebar
permalink: faq.html
keywords: faq, questions, requirements, service connector, object store, object storage, aws, azure, bucket, cluster, aggregate, s3, storage class, standard, inactive data reporting, auto, volume tiering policy, policy, tiering policy, snapshot, cold, inactive, infrequent
summary: This FAQ can help if you're just looking for a quick answer to a question.
---

= Cloud Tiering technical FAQ
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
This FAQ can help if you're just looking for a quick answer to a question.

== ONTAP

The following questions relate to ONTAP.

=== What are the requirements for my ONTAP cluster?

It depends on where you tier the cold data. Refer to the following:

* link:task_preparing.html#preparing-your-ontap-clusters[Preparing to tier inactive data to AWS S3]
* link:task_preparing_azure.html#preparing-your-ontap-clusters[Preparing to tier inactive data to Azure Blob storage]
* link:task_preparing_google.html#preparing-your-ontap-clusters[Preparing to tier inactive data to Google Cloud Storage]
* link:task_preparing_storagegrid.html#preparing-your-ontap-clusters[Preparing to tier inactive data to StorageGRID]

=== Does Cloud Tiering enable inactive data reporting?

Yes, Cloud Tiering enables inactive data reporting on each aggregate. This setting enables us to identify the amount of inactive data that can be tiered to low-cost object storage.

=== Can I tier data from NAS volumes and SAN volumes?

You can use Cloud Tiering to tier data from NAS volumes to the public cloud and from SAN volumes to a private cloud using StorageGRID.

== Object storage

The following questions relate to object storage.

=== Which object storage providers are supported?

Amazon S3, Azure Blob storage, Google Cloud Storage, and StorageGRID using the S3 protocol are supported.

=== Can I use my own bucket/container?

Yes, you can. When you set up data tiering, you have the choice to add a new bucket/container or to select an existing bucket/container.

=== Which public cloud regions are supported?

* link:reference_aws_support.html[Supported AWS regions]
* link:reference_azure_support.html[Supported Azure regions]
* link:reference_google_support.html[Supported Google Cloud regions]

=== Which S3 storage classes are supported?

Cloud Tiering supports data tiering to the _Standard_, _Standard-Infrequent Access_, _One Zone-IA_, or _Intelligent_ storage class. See link:reference_aws_support.html[Supported S3 storage classes] for more details.

=== Which Azure Blob access tiers are supported?

Cloud Tiering automatically uses the _Hot_ access tier for your inactive data. We plan to add support for the _Cool_ access tier in a future release.

=== Which storage classes are supported for Google Cloud Storage?

Cloud Tiering uses the _Standard_ storage class for inactive data.

=== Does Cloud Tiering use one object store for the entire cluster or one per aggregate?

One object store for the entire cluster.

=== Can I apply policies to my object store to move data around independent of tiering?

No, Cloud Tiering does not support object lifecycle management rules that move or delete data from object stores.

== NetApp Service Connector

The following questions relate to the NetApp Service Connector.

=== What is the Service Connector?

The Service Connector is NetApp software that communicates with ONTAP clusters to discover information about active and inactive data, and to set up data tiering. For more details, see link:concept_architecture.html[How Cloud Tiering works].

=== Where can I run the Service Connector?

* When tiering cold data to S3, the Service Connector can reside in an AWS VPC or on your premises.
* When tiering cold data to Blob storage, the Service Connector must reside in an Azure VNet.
* When tiering cold data to Google Cloud Storage, the Service Connector must reside in a Google Cloud Platform VPC.
* When tiering cold data to StorageGRID, the Service Connector must reside on an on premises Linux host.

=== How do you name the instance/virtual machine for the Service Connector?

The name of the Service Connector is prefixed with "Service-connector."

== Networking

The following questions relate to networking.

=== What are the networking requirements?

* The ONTAP cluster initiates an HTTPS connection over port 443 to a public cloud object storage provider.

* For StorageGRID, the ONTAP cluster initiates a connection over port 80.
+
ONTAP reads and writes data to and from object storage. The object storage never initiates, it just responds.

* The NetApp Service Connector needs an outbound HTTPS connection over port 443 to your ONTAP clusters, to the object store, and to the Cloud Tiering service.

For more details, see:

* link:task_preparing.html[Preparing to tier inactive data to AWS S3]
* link:task_preparing_azure.html[Preparing to tier inactive data to Azure Blob storage]
* link:task_preparing_google.html[Preparing to tier inactive data to Google Cloud Storage]
* link:task_preparing_storagegrid.html[Preparing to tier inactive data to StorageGRID]

== Permissions

The following questions relate to permissions.

=== What permissions are required in AWS?

Permissions are needed to install the Service Connector:

* link:task_preparing.html#setting-up-an-aws-account-for-the-service-connector[These permissions are required to deploy the Service Connector in an AWS VPC]
* link:task_installing_service_connector.html#providing-permissions-to-an-aws-account[These permissions are required when you deploy the Service Connector on an on-premises Linux host]

A different set of permissions are required link:task_preparing.html#preparing-aws-s3-for-data-tiering[to manage the S3 bucket].

=== What permissions are required in Azure?

Permissions are needed link:task_preparing_azure.html#granting-azure-permissions[to deploy the Service Connector in an Azure VNet].

During deployment, Cloud Tiering creates and assigns a role to the Service Connector that provides the required permissions so ONTAP can tier inactive data to Azure Blob storage.

=== What permissions are required in Google Cloud Platform?

* Permissions are needed for the GCP user who will deploy the Service Connector in GCP from Cloud Tiering.

* Permissions are needed for a service account that has storage access keys.

* Permissions are needed for a service account that you'll associate with the Service Connector VM instance.

For details, see link:task_preparing_google.html[Preparing to tier inactive data to Google Cloud Storage].

=== What permissions are required for StorageGRID?

link:task_preparing_storagegrid.html#preparing-storagegrid[S3 permissions are needed].
