---
sidebar: sidebar
permalink: faq.html
keywords: faq, questions, requirements, service connector, object store, object storage, aws, azure, bucket, cluster, aggregate, s3, storage class, standard, inactive data reporting, auto, volume tiering policy, policy, tiering policy, snapshot, cold, inactive, infrequent
summary: Here are some answers to common questions.
---

= Cloud Tiering technical FAQ
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
This FAQ can help if you're just looking for a quick answer to a question.

== What are the requirements for my ONTAP cluster?

You need a NetApp AFF system running ONTAP 9.4 or later, with a network connection to your object storage provider. For details, see link:task_preparing.html#preparing-your-ontap-cluster[Preparing your ONTAP cluster].

== Which object storage providers are supported?

AWS S3 is supported at this time. Support is coming soon for Microsoft Azure, Google Cloud Platform, and StorageGRID Webscale.

== Which S3 regions are supported?

include::/_include/s3regions.adoc[]

== Which S3 storage classes are supported?

Cloud Tiering supports data tiering to the S3 Standard storage class. It does not support any other storage classes.

== Does Cloud Tiering create one S3 bucket for the entire cluster or one per aggregate?

One bucket for the entire cluster.

== What is the Service Connector?

The Service Connector is NetApp software that communicates with ONTAP clusters to discover information about hot and cold data and to set up data tiering.

== Where can I run the Service Connector?

In AWS. Support for Microsoft Azure is coming soon.

== How do you name the EC2 instance for the Service Connector?

The EC2 instance name for the Service Connector is prefixed with "Service-connector."

== Which volume tiering policy does Cloud Tiering apply to each volume?

When you select the volumes that you want to tier, Cloud Tiering applies the _Auto_ volume tiering policy to each volume. This policy tiers Snapshot copies and cold user data from the active file system to object storage.

== Does Cloud Tiering enable inactive data reporting?

Yes, Cloud Tiering enables inactive data reporting on each aggregate. This setting enables us to identify the amount of inactive (cold) data that can be tiered to low-cost object storage.
