---
redirect: occm/concept_cloud_tiering.html
sidebar: sidebar
permalink: reference_storage_providers.html
keywords: object storage provider, provider, cloud provider, aws, amazon, s3, microsoft azure, azure, gcp, google, google cloud storage, storagegrid
summary: Cloud Tiering can tier inactive data from an ONTAP cluster to a public cloud or private cloud.
---

= Supported object storage providers
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Tiering can tier inactive data from an ONTAP cluster to a public cloud (AWS S3, Microsoft Azure Blob storage, or Google Cloud Storage) or to a private cloud (StorageGRID).

== AWS S3

* link:task_quick_start.html[Quick start for AWS]
* link:reference_aws_support.html[Supported S3 storage classes and regions]

== Azure Blob storage

* link:task_quick_start_azure.html[Quick start for Azure]
* link:reference_azure_support.html[Supported Azure Blob access tiers and regions]

== Google Cloud Storage

* link:task_quick_start_google.html[Quick start for Google Cloud Storage]
* link:reference_google_support.html[Supported Google Cloud storage classes and regions]

== StorageGRID using the S3 protocol

link:task_quick_start_storagegrid.html[Quick start for StorageGRID]
